### ISSUE TITLE
表の間隔

### ISSUE THREAD

**Issue by RyukiYasunaga** [Osuka-Sugimoto-Lab/Osuka-Sugimoto-lab_thesis_template#5]
表の間隔が狭くなる
サンプルコード

\begin{table}[t]
    \caption{Trajectory plan expected to proceed in an L-shape}
    \label{trajectory_plan}
    \centering
    \begin{tabular}{ccc}\hline
    Time [s] & Left motor input value & Right motor input value \\ \hline \hline
    13 & 1 & 1 \\ 
    10 & 1 & 0.3 \\ 
    15 & 1 & 1 \\ \hline
    \end{tabular}
  \end{table}

  \begin{table}[t]
    \caption{Trajectory plan expected to go in a circle shape Version 1}
    \label{curb_03}
    \centering
    \begin{tabular}{ccc}\hline
        Time [s] & Left motor input value & Right motor input value \\ \hline \hline
        60 & 1 & 0.3 \\ \hline
        \end{tabular}
  \end{table}

  \begin{table}[t]
    \caption{Trajectory plan expected to go in a circle shape Version 2}
    \label{curb_05}
    \centering
    \begin{tabular}{ccc}\hline
        Time [s] & Left motor input value & Right motor input value \\ \hline \hline
        60 & 1 & 0.5 \\ \hline
        \end{tabular}
  \end{table}

**Comment by jignoah** [comment]
対応しました
styファイルのみの更新で大丈夫です
