### ISSUE TITLE
minipageのsubcaptionが太字になる

### ISSUE THREAD

**Issue by RyukiYasunaga** [Osuka-Sugimoto-Lab/Osuka-Sugimoto-lab_thesis_template#6]
minipageを使って複数の図を挿入するとき，captionは問題ないが，subcaptionの文字だけ太字になってしまう

サンプルコード
[trajectory_3unit.pdf](https://github.com/Osuka-Sugimoto-Lab/Osuka-Sugimoto-lab_thesis_template/files/14059907/trajectory_3unit.pdf)
[trajectory_5unit_3unit_same.pdf](https://github.com/Osuka-Sugimoto-Lab/Osuka-Sugimoto-lab_thesis_template/files/14059908/trajectory_5unit_3unit_same.pdf)

\begin{figure}[t]
    \begin{minipage}[b]{\columnwidth}
     \centering
     \includegraphics[width=.8\columnwidth]{./figure/trajectory_3unit.pdf}
     \subcaption{Trajectory followed by each unit of ``Ryugu-no-tsukai" with 3~units}
     \label{trajectory_3unit}
   \end{minipage}\\%
   \begin{minipage}[b]{\columnwidth}
    \centering
    \includegraphics[width=.8\columnwidth]{./figure/trajectory_5unit_3unit_same.pdf}
    \subcaption{Trajectory followed by each unit of ``Ryugu-no-tsukai" with 5~units}
    \label{trajectory_5unit_3unit_same}
   \end{minipage}
   \caption{Trajectory followed by each unit of ``Ryugu-no-tsukai"}
\end{figure}

**Comment by jignoah** [comment]
対応しました
