### ISSUE TITLE
参考文献の著者が多い場合にet al.で省略したい

### ISSUE THREAD

**Issue by katayama-takahito** [Osuka-Sugimoto-Lab/Osuka-Sugimoto-lab_thesis_template#7]
タイトルの通り, 参考文献で著者が多い場合に全て表示されるので, et al. で省略ができるようにしたい.

**Comment by jignoah** [comment]
3名以上の著者の場合 et al.で省略できるbstを用意しました．
osukalab_bibstyle.bstを導入の上
\bibliographystyle{osukalab_bibstyle}             
\bibliography{myref}
とすれば適用できます．
